/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { registerRoute, setCatchHandler } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, matchPrecache } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all assets generated by Vite
const manifest = (self as unknown as { __WB_MANIFEST?: unknown }).__WB_MANIFEST ?? [];
precacheAndRoute(manifest as string[]);

// Cache API responses (network first with fallback)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 }),
    ],
  })
);

// Cache images (cache first)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 604800 }),
    ],
  })
);

// Cache static assets (cache first)
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'asset-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 2592000 }),
    ],
  })
);

// Handle fallback to index.html for SPA routing
setCatchHandler(async (ctx) => {
  const event = ctx.event as unknown as FetchEvent;
  if (event.request.mode === 'navigate') {
    return matchPrecache('/index.html');
  }
  return new Response('Not Found', { status: 404 });
});

// ── Push Notifications ───────────────────────────────────────────────

const AUDIO_FILES: Record<string, string> = {
  critical: '/audio/alert-critical.wav',
  warning: '/audio/alert-warning.wav',
  message: '/audio/message.wav',
  visit: '/audio/visit-start.wav',
  default: '/audio/alert-info.wav',
};

self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return;

  const payload = event.data.json();
  const { title, body, type, severity, patientId, url } = payload;

  const icon = severity === 'critical' ? '/pwa-192x192.png' : '/pwa-512x512.png';
  const tag = patientId ? `${type}-${patientId}` : type;
  const audioFile = AUDIO_FILES[severity || type || 'default'] || AUDIO_FILES.default;

  const options: NotificationOptions = {
    body,
    icon,
    badge: '/pwa-192x192.png',
    tag,
    data: { url, patientId, type },
    requireInteraction: severity === 'critical',
  };
  (options as unknown as { actions: Array<{ action: string; title: string }> }).actions = [
    { action: 'open', title: 'Ver detalhes' },
    { action: 'dismiss', title: 'Dispensar' },
  ];

  event.waitUntil(
    (async () => {
      await self.registration.showNotification(title, options);

      // Play audio notification (best-effort)
      try {
        const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
        for (const client of clients) {
          client.postMessage({
            type: 'NOTIFICATION_SOUND',
            audioFile,
            severity,
          });
        }
      } catch (e) {
        // Silent fail - audio is best-effort
      }
    })()
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  if (event.action === 'dismiss') return;

  const targetUrl = event.notification.data?.url || '/alerts';

  event.waitUntil(
    (async () => {
      const allClients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of allClients) {
        if ('focus' in client) {
          client.focus();
          client.navigate(targetUrl);
          return;
        }
      }
      if (self.clients.openWindow) {
        self.clients.openWindow(targetUrl);
      }
    })()
  );
});

// Handle messages from the app (for audio playback)
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
