/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, matchPrecache } from 'workbox-precaching';

clientsClaim();

// Precache all assets generated by Vite
const manifest = self.__WB_MANIFEST || [];
precacheAndRoute(manifest);

// Cache API responses (network first with fallback)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 }),
    ],
  })
);

// Cache images (cache first)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 604800 }),
    ],
  })
);

// Cache static assets (cache first)
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'asset-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 2592000 }),
    ],
  })
);

// Handle fallback to index.html for SPA routing
import { setCatchHandler } from 'workbox-routing';
setCatchHandler(async ({ event }) => {
  if (event.request.mode === 'navigate') {
    return matchPrecache('/index.html');
  }
  return Response.error('Not Found', { status: 404 });
});

// ── Push Notifications ───────────────────────────────────────────────

const AUDIO_FILES: Record<string, string> = {
  critical: '/audio/alert-critical.mp3',
  warning: '/audio/alert-warning.mp3',
  message: '/audio/message.mp3',
  visit: '/audio/visit-start.mp3',
  default: '/audio/alert-info.mp3',
};

self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return;

  const payload = event.data.json();
  const { title, body, type, severity, patientId, url } = payload;

  const icon = severity === 'critical' ? '/pwa-192x192.png' : '/pwa-512x512.png';
  const tag = patientId ? `${type}-${patientId}` : type;
  const audioFile = AUDIO_FILES[severity || type || 'default'] || AUDIO_FILES.default;

  const options: NotificationOptions = {
    body,
    icon,
    badge: '/pwa-192x192.png',
    tag,
    data: { url, patientId, type },
    requireInteraction: severity === 'critical',
    actions: [
      { action: 'open', label: 'Abrir', title: 'Ver detalhes' },
      { action: 'dismiss', label: 'Dispensar', title: 'Dispensar' },
    ],
  };

  event.waitUntil(
    (async () => {
      await self.registration.showNotification(title, options);

      // Play audio notification (best-effort)
      try {
        const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
        for (const client of clients) {
          client.postMessage({
            type: 'NOTIFICATION_SOUND',
            audioFile,
            severity,
          });
        }
      } catch (e) {
        // Silent fail - audio is best-effort
      }
    })()
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event: ExtendableEvent) => {
  event.notification.close();

  if (event.action === 'dismiss') return;

  const targetUrl = event.notification.data?.url || '/alerts';

  event.waitUntil(
    (async () => {
      const allClients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of allClients) {
        if ('focus' in client) {
          client.focus();
          client.navigate(targetUrl);
          return;
        }
      }
      if (self.clients.openWindow) {
        self.clients.openWindow(targetUrl);
      }
    })()
  );
});

// Handle messages from the app (for audio playback)
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
